defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

input_dir: '/home/sebalzer/Documents/Projects/Grand_Rounds/Zertifikate_Jan_2024'
rename_dict: {'Name (Originalname)': 'name', 'Benutzer-E-Mail:': 'mail', 'Dauer (Minuten)': 'duration'}